import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { FaBeer } from "react-icons/fa";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
        <title>Next Gen Coder | Blog Website</title>
      </Head>

      <nav className="px-4 py-4 bg-black text-white flex justify-between">
        <img src="http://localhost:3000/logo.png" alt="logo" className="h-8" />
        <ul className="flex justify-center space-x-14">
          <Link href="/">
            <li className=" font-bold cursor-pointer">Home</li>
          </Link>
          <Link href="/about">
            <li className=" font-bold cursor-pointer">About</li>
          </Link>
          <Link href="/blog">
            <li className=" font-bold cursor-pointer">Blog</li>
          </Link>
          <Link href="/contact">
            <li className=" font-bold cursor-pointer">Contacts</li>
          </Link>
        </ul>
      </nav>
      <main className="bg-[#b3ffff] py-40 font-serif">
        <div className="flex bg-[#85adad] justify-center py-8">
          <div className="main   pl-9 ">
            <div className="text-5xl">
              The best coding blog in the internet!
            </div>
            <p className="py-3 w-1/2">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero
              aperiam id quidem ex reprehenderit hic quisquam doloremque totam.
              Laborum ex provident dolorum eum? Iste quas eligendi nobis enim
              exercitationem vero!
            </p>
            <div className="buttons">
              <button className="bg-[#5ce1e6] px-2 mx-1 py-2 rounded-2xl text-white hover:text-slate-900 hover:bg-white border-2 hover:border-[#5ce1e6] border-[#5ce1e6] active:bg-[#5ce1e6]">
                Explore
              </button>
              <button className="bg-[#5ce1e6] px-3 py-2 rounded-2xl text-white hover:text-slate-900 hover:bg-white border-2 hover:border-[#5ce1e6] border-[#5ce1e6] active:bg-[#5ce1e6]">
                Contact Us Me
              </button>
            </div>
          </div>
          <div className="flex items-center pr-20 ">
            <img src="http://localhost:3000/image/1.png" alt="image" className="rounded-lg"/>
          </div>
        </div>
      </main>
    </>
  );
}
